# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Continuous Learning
email: laura.stone@alumni.carleton.edu
description: > # this means to ignore newlines until "baseurl:"
  Learn the DevOps. Discover the worlds of Go, Python, and Cloud Computing.
  Be the change you wish to see in the world. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tyrostone.github.io" # the base hostname & protocol for your site
twitter_username: tyrostone
github_username:  tyrostone

# Build settings
markdown: kramdown
include:
  - "/assets"